// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BulkUpdateResponse struct {
	Success   bool     `json:"success"`
	FailedIds []string `json:"failedIds"`
}

type Mutation struct {
}

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Stock       int     `json:"stock"`
}

type ProductInput struct {
	ID          string   `json:"id"`
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	Price       *float64 `json:"price,omitempty"`
	Stock       *int     `json:"stock,omitempty"`
}

type Query struct {
}
